name: Publish twenty-commons

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./libraries/twenty2-core
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          build-root-directory: ./libraries/twenty2-core
          gradle-executable: ./libraries/twenty2-core/gradlew
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}