name: Publish Core

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Make gradlew executable
        run: chmod +x ./libraries/twenty2-core/gradlew
      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
          build-root-directory: ./libraries/twenty2-core
          gradle-executable: ./libraries/twenty2-core/gradlew
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}